### ISSUE TITLE
how can I get a bigger image without blur ?

### ISSUE THREAD

**Issue by DreamerCorey** [paulovap/qtpdfium#1]
Hi, paulovap .

I'm using your project  in my free software. 
https://sourceforge.net/projects/ccseer/

Now, I get a problem when I was trying to read a bigger image . 

QPdfium::page()->data()->image(   scale   );
The issue is the parameter 'scale' .  When I set a  num bigger than 1 , the result is not very clear.

what should I do.

**Comment by paulovap** [comment]
Hey @DreamerCorey,

when scale is 1 it means with will render the image the at the natural width and height of the pdf page. (you can check it QPdfiumPage::width and QPdfiumPage::height).

If you want to render the image in a higher quality you can increase the scale, let's say to 2. So the rendered image will have  QPdfiumPage::width()*2 width and QPdfiumPage::height()*2 height. If that does not happen, then there is a bug.

**Comment by DreamerCorey** [comment]
The code is ok, actually.

The problem is , the quality of image has changed  if you scaled it double size.

**Comment by paulovap** [comment]
Is it possible to make available the pdf file that you are using so I can see what's wrong? Maybe there is an embedded bitmap in it?

**Comment by DreamerCorey** [comment]
![Uploading I9GN_E4]_G)T(LLPZGS%OU4.jpg…]()

I just tried a lot. 
I might be wrong  about the the quality of scaled image . Sorry... :cry: 
But can I make image more sharp ?

**Comment by DreamerCorey** [comment]
![Uploading I9GN_E4]_G)T(LLPZGS%OU4.jpg…]()

**Comment by DreamerCorey** [comment]
![i9gn_e4 _g t llpzgs ou4](https://cloud.githubusercontent.com/assets/3081374/10316847/f596c10c-6c93-11e5-981e-e1c8171fb25f.jpg)

**Comment by DreamerCorey** [comment]
Ummm...
Thx for your help . :smile:

**Comment by paulovap** [comment]
So, what was the problem?

**Comment by DreamerCorey** [comment]
![i9gn_e4 _g t llpzgs ou4](https://cloud.githubusercontent.com/assets/3081374/10331514/a36f9dc0-6d08-11e5-8bad-f09fc009d99a.jpg)

It is different if you look at the pic.  
I want make the pdf render more sharp  and more clear.

**Comment by paulovap** [comment]
Hi @DreamerCorey ,

Just tested here rendering the first page with scale 1.0 and 3.0. It worked fine. 
![qtpdfium_test](https://cloud.githubusercontent.com/assets/2519883/10337525/9d029e88-6cd6-11e5-8521-7b83eb7af435.png)

**Comment by DreamerCorey** [comment]
Ah.... I'll test it on Windows tomorrow.

Thanks, Thank you very much.

**Comment by paulovap** [comment]
Heres the code that generated those two images.

``` cpp
auto m_pdfium  = new QPdfium("iso.pdf");
QImage img;
img = m_pdfium->page(0).data()->image(3);
img.save(QString("test_3.jpg"), "jpg", 100);
img = m_pdfium->page(0).data()->image(1);
img.save(QString("test_1.jpg"), "jpg", 100);
```

**Comment by DreamerCorey** [comment]
It turns out  it's the platform differences.  I tested the code on os x , that's why image is blur
