### ISSUE TITLE
Visual C++ 14 can no longer build since upgrade of pdfium

### ISSUE THREAD

**Issue by pinaraf** [paulovap/qtpdfium#17]
Hi

It looks like since the upgrade of the bundled pdfium version VC++ is no longer able to build QtPdfium.

Here is the compilation command : 
```
        cl -c -FIQtPdfiumDepends -YuQtPdfiumDepends -Fp.pch\release\Qt5Pdfium_pch.pch -nologo -Zc:wchar_t -FS -Zc:strictStrings -Zc:throwingNew -O2 -MD -W3 -w34100 -w34189 -w44996 -w44456 -w44457 -w44458 -wd4577 -wd4467 -D_HAS_EXCEPTIONS=0 -GR -DUNICODE -DWIN32 -D__QT__ -DOPJ_STATIC -DPNG_PREFIX -DPNG_USE_READ_MACROS -DQT_NO_VERSION_TAGGING -DQT_BUILD_PDFIUM_LIB -DQT_BUILDING_QT -D_CRT_SECURE_NO_WARNINGS -D_USE_MATH_DEFINES -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x040800 -DFT2_BUILD_LIBRARY -DQT_NO_EXCEPTIONS -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DNDEBUG -D_WINDLL -IC:\Users\snoopy\Documents\pdfium-test\qtpdfium\src\pdfium -I. -I..\..\include -I..\..\include\QtPdfium -IC:/Users/snoopy/Documents/pdfium-test/qtpdfium/build32/include/QtPdfium/5.5.0 -IC:/Users/snoopy/Documents/pdfium-test/qtpdfium/build32/include/QtPdfium/5.5.0/QtPdfium -Itmp -IC:\Users\snoopy\Documents\pdfium-test\qtpdfium\src\3rdparty\pdfium -IC:\Users\snoopy\Documents\pdfium-test\qtpdfium\src\3rdparty\pdfium\third_party\freetype\include -IC:\Users\snoopy\Documents\pdfium-test\qtpdfium\src\3rdparty\pdfium\third_party\freetype\include\freetype -IC:\Qt\5.7\msvc2015\include\QtCore\5.7.1 -IC:\Qt\5.7\msvc2015\include\QtCore\5.7.1\QtCore -IC:\Qt\5.7\msvc2015\include -IC:\Qt\5.7\msvc2015\include\QtGui -IC:\Qt\5.7\msvc2015\include\QtANGLE -IC:\Qt\5.7\msvc2015\include\QtCore -I.moc\release -IC:/utils/my_sql/my_sql/include -IC:/utils/postgresql/pgsql/include -IC:\Qt\5.7\msvc2015\mkspecs\win32-msvc2015 -Fo.obj\release\ @C:\Users\snoopy\AppData\Local\Temp\nm8758.tmp
cba_annotiterator.cpp
```

And there are then a lot of various errors. Thanks to VC++, the error messages are in french… So I will translate some of them

```
C:\Users\snoopy\Documents\pdfium-test\qtpdfium\src\3rdparty\pdfium\core/fxcrt/fx
_memory.h(29): error C2065: '__noinline__' : undefined identifier
C:\Users\snoopy\Documents\pdfium-test\qtpdfium\src\3rdparty\pdfium\core/fxcrt/fx
_memory.h(29): error C4430: missing type specification - int is used by default. Notice: C++ does not use int by default.
C:\Users\snoopy\Documents\pdfium-test\qtpdfium\src\3rdparty\pdfium\core/fxcrt/fx
_memory.h(29): error C2448: '__attribute__' : function style initializer seems to be a function declaration
C:\Users\snoopy\Documents\pdfium-test\qtpdfium\src\3rdparty\pdfium\core/fxcrt/fx
_memory.h(43): error C3861: 'FX_OutOfMemoryTerminate' : missing identifier
```

And so on and so on…
I'll try to find out what is missing here, but I would be happy if you have any hint to help me find out the breaking stuff…

Thanks

**Comment by pinaraf** [comment]
I found the issue: 
```
210e030ae0 core/fxcrt/fx_system.h         (Paulo Pinheiro    2017-01-16 21:18:32 +0100  33) #define _FXM_PLATFORM_QT_       5
```

When you did that, you created a small mess with the following #if #elsif : when compiling under MSVC++, NEVER_INLINE should always be defined as ``__declspec(noinline)``…
I'll try to figure out a solution during the week-end if I can get enough spare time, otherwise I'll continue searching next week.

**Comment by pinaraf** [comment]
I've found a way to fix this issue. I lost a lot of time going the wrong way, but now I have got something working with a relatively small patch. Since this imply a pdfium patch, I will soon send you a PR for you pdfium repository, and another one for this repository (hopefully the fixes don't need each other).

**Comment by pinaraf** [comment]
The fixes are in paulovap/pdfium#1 and in PR #20

**Comment by paulovap** [comment]
Hi @pinaraf, sorry for taking so long to respond. I needed to resurrect my old Windows box to test this.
It seems to be crashing when compiling with Visual Studio 2015. I will try to figure out what is wrong. It seems to be related to the deletion of CPDF_TextPage.

Config: Using QtTest library 5.8.0, Qt 5.8.0 (i386-little_endian-ilp32 shared (dynamic) debug build; by MSVC 2015)
PASS   : CppTest::initTestCase()
PASS   : CppTest::test_protectedPdf()
A crash occurred in C:\Users\Natalia\Desktop\PAULO\build-cpp-Desktop_Qt_5_8_0_MSVC2015_32bit-Debug\debug\tst_cpp.exe.
Function time: 135ms Total time: 192ms

Exception address: 0x00E0443A
Exception code   : 0xc0000005
Nearby symbol    : CPDF_DocPageData::IsForceClear

Stack:
#  1: QTestLog::enterTestFunction() - 0x0FBE2BC6
#  2: UnhandledExceptionFilter() - 0x75E5D150
#  3: LdrSetAppCompatDllRedirectionCallback() - 0x76F82860
#  4: RtlSubscribeWnfStateChangeNotification() - 0x76F601D0

The program has unexpectedly finished.

**Comment by pinaraf** [comment]
Hi @paulovap 

I'll try to build cleanly tomorrow, but it worked without crashing (and both unit tests and my application work). Maybe something I forgot to commit, I'll check that.

**Comment by jikson26** [comment]
@pinaraf Did you ever get a chance to review it? Would be of great help to me. Please :)

**Comment by pinaraf** [comment]
Hi @jikson26 and @paulovap 

Sorry I have been really busy and sick in the past days so I did not have much time to look into this.
I will do my best to fix that in the next days, thanks for reminding me of the issue here.

**Comment by jikson26** [comment]
No worries at all. Please take care of yourself. Please let me know if there's any way I can help.

I attempted to build from your PR.

using:

win 10

```
qmake -r -spec win32-msvc2015
jom
```

```
..\3rdparty\pdfium\fpdfsdk\fpdfview.cpp(681): error C2065: 'CFX_WindowsDevice': undeclared identifier
..\3rdparty\pdfium\fpdfsdk\fpdfview.cpp(681): error C2065: 'CFX_WindowsDevice': undeclared identifier
..\3rdparty\pdfium\fpdfsdk\fpdfview.cpp(681): error C2672: 'pdfium::MakeUnique': no matching overloaded function found
..\3rdparty\pdfium\fpdfsdk\fpdfview.cpp(681): error C2974: 'pdfium::MakeUnique': invalid template argument for 'T', type expected
..\3rdparty\pdfium\third_party/base/ptr_util.h(69): note: see declaration of 'pdfium::MakeUnique'
..\3rdparty\pdfium\fpdfsdk\fpdfview.cpp(688): error C2065: 'CFX_WindowsDevice': undeclared identifier
..\3rdparty\pdfium\fpdfsdk\fpdfview.cpp(688): error C2146: syntax error: missing ';' before identifier 'WinDC'
..\3rdparty\pdfium\fpdfsdk\fpdfview.cpp(688): error C3861: 'WinDC': identifier not found
..\3rdparty\pdfium\fpdfsdk\fpdfview.cpp(689): error C2065: 'WinDC': undeclared identifier
..\3rdparty\pdfium\fpdfsdk\fpdfview.cpp(689): error C2228: left of '.GetDeviceCaps' must have class/struct/union
..\3rdparty\pdfium\fpdfsdk\fpdfview.cpp(689): note: type is 'unknown-type'
..\3rdparty\pdfium\fpdfsdk\fpdfview.cpp(696): error C2065: 'WinDC': undeclared identifier
..\3rdparty\pdfium\fpdfsdk\fpdfview.cpp(696): error C2228: left of '.StretchDIBits' must have class/struct/union
..\3rdparty\pdfium\fpdfsdk\fpdfview.cpp(696): note: type is 'unknown-type'
..\3rdparty\pdfium\fpdfsdk\fpdfview.cpp(698): error C2065: 'WinDC': undeclared identifier
..\3rdparty\pdfium\fpdfsdk\fpdfview.cpp(698): error C2228: left of '.SetDIBits' must have class/struct/union
```

**Comment by pinaraf** [comment]
Hi

I just rebuilt from scratch, in a clean environment. I indeed forgot to commit a file, my bad. I have updated the PR on the pdfium repository.
Regarding the tests, they worked flawlessly once I could build everything.
Be careful, Windows is not to be trusted regarding the good old DLL-Hell :) I chose to purge the previous installation of QtPdfium before running the tests.

```
C:\Users\snoopy\Documents\tmp\qtpdfium\build\lib>tst_cpp.exe
********* Start testing of CppTest *********
Config: Using QtTest library 5.7.1, Qt 5.7.1 (i386-little_endian-ilp32 shared (dynamic) release build; by MSVC 2015)
PASS   : CppTest::initTestCase()
PASS   : CppTest::test_protectedPdf()
PASS   : CppTest::test_documentDeletion()
PASS   : CppTest::test_extractText()
PASS   : CppTest::test_countChars()
PASS   : CppTest::test_countTextRects()
PASS   : CppTest::test_extractTextRect()
PASS   : CppTest::test_invalidPdf()
PASS   : CppTest::test_openPdf()
PASS   : CppTest::test_countPages()
PASS   : CppTest::test_getPages()
PASS   : CppTest::test_pageSize()
PASS   : CppTest::test_renderPage()
PASS   : CppTest::cleanupTestCase()
Totals: 14 passed, 0 failed, 0 skipped, 0 blacklisted, 3125ms
********* Finished testing of CppTest *********
```

Basically, to get that:
- git clone -b fixMsvcCompat --recursive git@github.com:pinaraf/qtpdfium.git
- cd qtpdfium
- mkdir build
- cd build
- qmake ..
- nmake
- mkdir tests
- cd tests
- qmake ..\..\tests
- nmake
- copy auto\cpp\release\tst_cpp.exe ..\lib
- cd ..\lib
- tst_cpp.exe


(I don't enjoy the windows developer experience very much…)

**Comment by ChengHuangUCAS** [comment]
Hi, @pinaraf  @paulovap , I did
- git clone -b fixMsvcCompat --recursive https://github.com/pinaraf/qtpdfium.git
- cd qtpdfium
- mkdir build
- cd build
- qmake ..
- nmake

in vs 2017 x64 command line on win10, and a lot of errors occured. 
It said something like ' **undefined "\_\_noinline\_\_"** (C2065) ', ' **unable to open "dirent.h"** (C1083) ' and several other errors seemed are generated by C2065 (like ' cannot find "FX_OutOfMemoryTerminate"(C3861) ', C4430, C2448 and so on). And they repeated dozens of times.
The same errors also occured when I was using Qt to build them directly.
I'm **not sure about the exact English words** of error messages because my OS is in Chinese. 
I've added C:\Qt\Qt5.10.0\5.10.0\winrt_x64_msvc2017\bin and  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\bin\Hostx64\x64 to my PATH.

**Comment by ChengHuangUCAS** [comment]
And after I changed the compiler to MinGW 32bit in Qt, 8 errors generated.
![image](https://user-images.githubusercontent.com/35071571/43311215-5a0dce1e-91bc-11e8-8323-0885e421b83d.png)
