### ISSUE TITLE
What is the license for qtpdfium ?

### ISSUE THREAD

**Issue by dfaure** [paulovap/qtpdfium#2]
Hello, there doesn't seem to be any license information for qtpdfium. Can you add the usual README.md, and/or LICENSE file, and license+copyright headers in the .cpp/.h files ?

Thanks !

**Comment by dfaure** [comment]
pdfium being BSD, the most convenient licence for qtpdfium would be BSD as well, but that's up to you ;)

**Comment by paulovap** [comment]
@dfaure You can consider it BSD. I will push the license later today.
