### ISSUE TITLE
QByteArray type pdf file how to load ah?

### ISSUE THREAD

**Issue by jlynet** [paulovap/qtpdfium#25]
QByteArray type pdf file how to load ah?

**Comment by paulovap** [comment]
If I understand your question correctly you want to load a pdf file from QByteArray.

Right now I haven't written an API for that, might be an interesting addition. 

But you can, as a workaround, flush your QByteArray into a temporary file. See:
http://doc.qt.io/qt-5/qtemporaryfile.html

**Comment by paulovap** [comment]
@ai930 did this solve it for you?
