### ISSUE TITLE
Build for iOS

### ISSUE THREAD

**Issue by paulocoutinhox** [paulovap/qtpdfium#26]
Hi,

I finished my script to build the PDFium to iOS. All is here with manual patchs:
https://github.com/prsolucoes/mobile-pdfium

But i have some issues after compile. All issues is described here:
https://github.com/prsolucoes/mobile-pdfium/issues/1

Can you help me?

**Comment by paulovap** [comment]
Sorry, I fail to see how this relates to this project qtpdfium.

**Comment by paulocoutinhox** [comment]
Hi,

It is working. If anyone wanna, it is building on travis and all instructions is here:
https://github.com/prsolucoes/mobile-pdfium

Thanks.
