### ISSUE TITLE
doesn't work on ios

### ISSUE THREAD

**Issue by douyw** [paulovap/qtpdfium#3]
Hi, thank for this great module.
I created a test app, and it works smoothly on my Mac(osx 10.12.1). But it cannot render the image on my iPad(iOS 10.0.1). Here are some log outputs:

> pageCount:  10
> pdfium_ valid:  true
> pageIndex =  1
> img.isNull() =  true
> img.width() =  0
> img.height() =  0

Any suggestion? Thank you.

By the way, the global PdfiumGlobal object failed to initialize the FPDF library. So, I commented out that line code. Instead, a temporary fix, using a global scope pointer to hold it, skiped that issue in my test app.

**Comment by douyw** [comment]
In addition, I defined a new method:
```cpp
void QPdfium::setFileContent(QByteArray const& data) {
    if (m_document) {
        FPDF_CloseDocument(m_document);
        m_pages.clear();
    }
    m_document = FPDF_LoadMemDocument(data.data(), data.length(), NULL);
    if (m_document)
        m_pageCount = FPDF_GetPageCount(m_document);
}

```
This allows me to read and set the pdf file content in app resource.

**Comment by paulovap** [comment]
Hi,

Thanks for reporting. I will look into that.

**Comment by paulovap** [comment]
Hi @douyw I tried to run/deploy a sample Qt application on a iOS simulator (I don't have a device anymore). And it seems that Qt 5.7 is broke for the latest XCode. So I am unable to test at the moment :T

**Comment by kangjoni76** [comment]
Same to me here for android jelly bean  , it seems that FPDF_LoadMemDocument always fail and causing crash. Confirmed only works for Linux and win desktop. Will try building from lastest chromium gift pdfium, but gn build was awkward for me ;(

**Comment by paulovap** [comment]
I am trying to track down the bug. I will check Android first since is easier to debug (I don't have iOS device). Maybe will come up with something in the next days.

**Comment by douyw** [comment]
These days I was occupied by another project. Thank you, @kangjoni76, FPDF_LoadMemDocument is the problem indeed. It can work if you load file from the disk, tested on both iOS and Android. Thank you, @paulovap for your time.
