### ISSUE TITLE
Severe Memoryleaks

### ISSUE THREAD

**Issue by m4xw** [paulovap/qtpdfium#6]
Hello,
sorry I can't submit a Patch at this time, but qtpdfium is leaking around 20MByte for every document.
Reason for this is a missing `FPDF_ClosePage(m_page)` in the QPdfiumPage deconstructor!

The QPdfium deconstructor should be like 
```
for(auto xPage: m_pages){
 xPage.reset(); // remove reference, invokes deconstructor
 m_pages.clear();
}
if(m_document)
 ....
```

Note: We need to free the pages BEFORE we close the document.

Without the change Pdfium itself leaks around 56000 allocations!

Simliar should be done in `setFileName()`

**Comment by paulovap** [comment]
#8b2565c12c07b9e49c29980d246b7d0a09d94867
